"""empty message

Revision ID: 42ce52fa6e09
Revises: 7e65265d67a5
Create Date: 2023-05-30 02:46:55.642202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ce52fa6e09'
down_revision = '7e65265d67a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
